#code to send CSV data to DataBase Table
import pandas as pd
from sqlalchemy import create_engine
from urllib.parse import quote  

#engine = create_engine("postgresql://postgres@localhost:5432/postgres", echo=False)
engine = create_engine('postgresql://postgres:%s@localhost:5432/postgres' % quote('postgres'))
#df = pd.read_csv("C:/Users/vnaga/Desktop/of/test/EnneWood_Data_12-05-2022_to_13-05-2022.csv", header=0)
df.to_sql("ennewood_test", con=engine)

In [38]:
df

,CreatedTime,SystemTime,SiteId,DBTime,DeviceId,E_gas_CO_cont_I__PV,E_gas_CO_cont_C__PV,VENT_CT__PV,BFW_p_B_CT__PV,Can_W_CP_A_CT__PV,...,Superficial_V__PV,CMB_AFR_C_rate_LT__PV,fr_C_rate_LT__PV,Superficial_VC__PV,Deaerator_LC_SP,Deaerator_LC_PV,Bug_F_DP__PV,E_gas_CO_cont_MA1__PV,Fluidized_bed_DP1__PV,Ecmz_Gas_DP__PV
0,2022-05-12 23:59:59.443000+00:00,2022-05-13 00:00:11+00:00,1,2022-05-13 00:00:12.938936+00:00,3,15.725,9.435000,85.599998,0,0,...,0.922797,24143.904297,14079.878906,0.922797,0,9.693054,0.614662,15.570001,9.024193,0.177469
1,2022-05-12 23:59:58.430000+00:00,2022-05-13 00:00:10+00:00,1,2022-05-13 00:00:11.936157+00:00,3,15.500,9.300000,84.599998,0,0,...,0.920613,24131.208984,14064.009766,0.920613,0,9.785278,0.615855,15.554999,9.007225,0.175048
2,2022-05-12 23:59:57.430000+00:00,2022-05-13 00:00:09+00:00,1,2022-05-13 00:00:10.924304+00:00,3,15.025,9.014999,84.449997,0,0,...,0.919243,24144.365234,14080.457031,0.919243,0,9.764465,0.607165,15.585001,8.995429,0.172722
3,2022-05-12 23:59:56.430000+00:00,2022-05-13 00:00:08+00:00,1,2022-05-13 00:00:09.912230+00:00,3,14.700,8.820001,85.300003,0,0,...,0.918418,24131.677734,14064.597656,0.918418,0,9.856689,0.602359,15.615000,8.990334,0.171259
4,2022-05-12 23:59:55.413000+00:00,2022-05-13 00:00:07+00:00,1,2022-05-13 00:00:08.903110+00:00,3,14.375,8.625000,84.949997,0,0,...,0.917492,24131.832031,14064.788086,0.917492,0,9.842957,0.602002,15.525000,8.989056,0.169969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85848,2022-05-12 00:00:04.380000+00:00,2022-05-12 00:00:16+00:00,1,2022-05-12 00:00:18.013808+00:00,3,6.825,4.110000,80.750000,0,0,...,0.919548,21826.076172,12994.198242,0.919548,0,-10.123108,0.629556,6.735000,9.019882,0.156828
85849,2022-05-12 00:00:03.477000+00:00,2022-05-12 00:00:15+00:00,1,2022-05-12 00:00:17.003762+00:00,3,6.850,4.035000,82.250000,0,0,...,0.919548,21821.478516,12992.282227,0.919548,0,-9.876648,0.629556,6.735000,9.019882,0.156716
85850,2022-05-12 00:00:02.477000+00:00,2022-05-12 00:00:14+00:00,1,2022-05-12 00:00:15.992353+00:00,3,6.725,3.915000,80.699997,0,0,...,0.921050,21855.837891,13006.598633,0.921050,0,-9.769897,0.619590,6.750000,9.020562,0.157252
85851,2022-05-12 00:00:01.477000+00:00,2022-05-12 00:00:13+00:00,1,2022-05-12 00:00:14.981630+00:00,3,6.525,3.975000,83.099998,0,0,...,0.922949,21851.609375,13004.836914,0.922949,0,-9.536499,0.617855,6.675000,9.021656,0.157711
85852,2022-05-12 00:00:00.460000+00:00,2022-05-12 00:00:12+00:00,1,2022-05-12 00:00:13.974585+00:00,3,6.625,3.840000,81.349998,0,0,...,0.924032,21886.361328,13019.317383,0.924032,0,-9.409973,0.617855,6.735000,9.021656,0.158080

#to convert string data to dateTime
df.DBTime=pd.to_datetime(df.DBTime)

In [43]:
type(pd.to_datetime(df.DBTime))

pandas.core.series.Series